# Generated by Django 2.2.9 on 2019-12-18 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_boast', models.BooleanField(default=True)),
                ('content', models.CharField(max_length=280)),
                ('author', models.CharField(max_length=20)),
                ('up_votes', models.IntegerField(default=0)),
                ('down_vote', models.IntegerField(default=0)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('net_votes', models.IntegerField(default=0)),
            ],
        ),
    ]
